Ml-survey service deployment scripts 3.9.0
project-sunbird/sunbird-devops pull request #2461
Opened 2021-04-23 13:52 UTC by sivakarthikeyanoptit

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-04-26 13:35 UTC, keshavprasadms commented on ansible/roles/stack-sunbird/templates/ml-survey-service.env
> +{{ml_cloud_config}}
What is this? How will we define this in private? where is the default for this? is the a dictionary, list, string, integer etc?

2021-04-26 13:36 UTC, keshavprasadms requested changes
Please check comments.

2021-04-26 13:45 UTC, keshavprasadms approved these changes

2021-04-27 06:27 UTC, G33tha approved these changes

2021-04-27 06:27 UTC, merged