feat: TG-949 Sunbird 3.8.0 GA fixes
project-sunbird/sunbird-devops pull request #2507
Opened 2021-05-07 10:58 UTC by keshavprasadms

2021-05-20 09:19 UTC, rjshrjndrn requested changes

2021-05-21 04:15 UTC, keshavprasadms commented on ansible/inventory/env/group_vars/all.yml
> +bootstrap_namespace: "{{ env }},flink-{{ env }},flink-kp-{{ env }}"
Requires changes in playbook level also and retesting, this implementation should be fine for now. Matches the jenkins input and is in accordance with many roles we have created and used this format.

2021-05-21 06:02 UTC, keshavprasadms commented on ansible/inventory/env/group_vars/all.yml
>    - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
done

2021-05-21 06:02 UTC, keshavprasadms commented on ansible/inventory/env/group_vars/all.yml
> +sunbird_ekstep_api_key: "{{ core_vault_sunbird_api_auth_token }}" #Authorization key (JWT) to access Ekstep APIs. Steps to generate this are documented on {{proto}}://github.com/project-sunbird/sunbi
done

2021-05-21 09:08 UTC, keshavprasadms commented on ansible/roles/postgresql-data-update/tasks/main.yml
> -- name: Verifying db users are present else creating them
Handled with a softlink - Please check these
https://github.com/project-sunbird/sunbird-devops/pull/2507/commits/c1ea970fbaf6940e3c0b129db42641ebb275bca4
https://github.com/project-sunbird/sunbird-devops/pull/2507/commits/960659c3c1fd7c34e2a974ef6d258af9d8d7dc7e

2021-05-21 09:09 UTC, keshavprasadms commented on ansible/inventory/env/group_vars/all.yml
>  postgresql_databases:
Please check https://github.com/project-sunbird/sunbird-devops/pull/2507#discussion_r636762226

2021-05-21 09:16 UTC, rjshrjndrn approved these changes

2021-05-21 09:16 UTC, rjshrjndrn commented
Nice work @keshavprasadms :tada:

2021-05-21 09:16 UTC, merged