Issue #SB-25388 for SSO in VDN
project-sunbird/sunbird-devops pull request #2802
Opened 2021-08-16 06:50 UTC by rajeevsathish

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-16 06:54 UTC, keshavprasadms commented on ansible/roles/stack-sunbird/templates/sunbird_player.env
> +crypto_encryption_key_external={{crypto_encryption_key_external}}
What’s the default value ? Or it doesn’t require a default is a mandatory variable?

2021-08-16 06:54 UTC, rjshrjndrn requested changes

2021-08-16 06:54 UTC, rjshrjndrn commented on ansible/roles/stack-sunbird/templates/sunbird_player.env
> +crypto_encryption_key_external={{crypto_encryption_key_external}}
@rajeevsathish can you please add comment on what's this variable for

2021-08-16 12:46 UTC, rjshrjndrn commented on ansible/roles/stack-sunbird/templates/sunbird_player.env
> +crypto_encryption_key_external={{crypto_encryption_key_external}}
@rajeevsathish encrypt what

2021-08-18 05:51 UTC, rjshrjndrn approved these changes

2021-08-18 05:51 UTC, rjshrjndrn commented
LGTM

2021-08-18 05:51 UTC, merged