SB-29553 - Added mapping reqired for user and org enhancements
project-sunbird/sunbird-devops pull request #3315
Opened 2022-04-26 13:45 UTC by karthik-tarento

2022-04-26 15:02 UTC, karthik-tarento commented
@reshmi-nair -- created PR as requested for SB-29553 story. This PR contains ES mappings for user and org.
Please review and merge

2022-04-28 06:53 UTC, amit-tarento requested changes

2022-04-28 06:53 UTC, amit-tarento commented on ansible/roles/es-mapping/files/mappings/userv3-mapping.json
> +    "profileDetails": {
Please take a look for the below and change accordingly
 "userType": {
      "type": "text",
      "fields": {
        "raw": {
          "type": "text",
          "analyzer": "keylower"
        }
      },
      "analyzer": "cs_search_analyzer",
      "search_analyzer": "cs_search_analyzer"
    },
    
    
    remove copy_to and fielddata= true as its not required

2022-04-28 06:53 UTC, amit-tarento commented on ansible/roles/es-mapping/files/mappings/userv3-mapping.json
> +        "photo": {
Do we need this field to be index, Is this field searchable and whats the significance for searching this field.

2022-04-28 06:53 UTC, amit-tarento commented on ansible/roles/es-mapping/files/mappings/userv3-mapping.json
> +              "type": "text",
Do we need this email field as text , Do we really need this field to be analyzed or apply fuzzy or auto search capability

2022-04-28 06:53 UTC, amit-tarento commented on ansible/roles/es-mapping/files/mappings/userv3-mapping.json
> +              "type": "text",
same as above comment for email field.

2022-04-28 06:53 UTC, amit-tarento commented on ansible/roles/es-mapping/files/mappings/userv3-mapping.json
> +              "fields": {
Please take a look again for all these fields and change the data type for fields if its not required to analyzed

2022-04-28 08:07 UTC, karthik-tarento commented
@amit-tarento @reshmi-nair -- closing this PR as we will have forked repo for devOps in our env. Will maintain the user mapping too in our forked repo for now.

2022-04-28 08:07 UTC, closed without merging