Add gcloud role and related tasks
project-sunbird/sunbird-devops pull request #3566
Opened 2022-10-18 08:27 UTC by santhosh-tg

Adding gcloud related role and updating CSP related  gcloud tasks.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-27 10:30 UTC, keshavprasadms commented on ansible/roles/gcp-cloud-storage/defaults/main.yml
> +# The folder path in gcloud storage to upload the files starting from the root of the container
This line still has reference as container. Please change it to bucket.

2022-10-27 10:32 UTC, keshavprasadms commented on ansible/roles/gcp-cloud-storage/meta/main.yml
> +dependencies:
Let's remove the meta directory. The expectation is that a user runs the bootstrap job and installs the required packages first.

2022-10-27 10:35 UTC, keshavprasadms commented on ansible/roles/gcp-cloud-storage/tasks/gcloud-auth.yml
> +    dest: /tmp/gcp_storage_key_file.json
Can we prefix this with some unique value that is specific for this run only only? For instance, if two jobs run at the same time on the same VM, chances are they will be overwritten. Maybe an epoch timestamp can give us certain level uniqueness.

2022-10-27 11:04 UTC, keshavprasadms requested changes
Please also add the private repo template variables required for this change.

2022-10-28 11:12 UTC, santhosh-tg commented
@keshavprasadms  addressed the comments, please review

2022-10-30 03:32 UTC, keshavprasadms approved these changes
Looks good. In the next PR, please also include the code to install gcloud packages using the bootstrap Jenkins job.

2022-10-30 03:33 UTC, merged