Add variables for report automation
project-sunbird/sunbird-devops pull request #3846
Opened 2023-06-19 12:13 UTC by Ashwiniev95

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-19 15:12 UTC, aks30 requested changes
Reviewed on 19 June 8:40 PM

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_refresh_token : "auth/realms/sunbird/protocol/openid-connect/token"
@Ashwiniev95 Remove API endpoints from here and put them as configs in the code.

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_folder_name : 6.0.0
@Ashwiniev95 Remove this

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_script_path : "/opt/sparkjobs/ml-analytics-service/migrations/lib"
@Ashwiniev95 Put below in constant not in here

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_folder_config : "/opt/sparkjobs/ml-analytics-service/migrations/releases/6.0.0/config/"
@Ashwiniev95 this we don't need here.

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_createdBy : "{{ ml_analytics_createdBy }}"
@Ashwiniev95 to check if this is required try to use the same as the above user

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_reports_key : "{{ ml_analytics_reports_key }}"
@Ashwiniev95 to confirm with Sachin if this is really needed in config

2023-06-19 15:12 UTC, aks30 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_update_tag : "{{ ml_analytics_update_tag }}"
@rakeshSgr To check with Amogh how can we identify these report Ids using API query. Else in release note we should put out steps to identify the same in pord and then pass it here using pvt repo

2023-06-20 11:19 UTC, Ashwiniev95 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_refresh_token : "auth/realms/sunbird/protocol/openid-connect/token"
Done

2023-06-20 11:20 UTC, Ashwiniev95 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_folder_name : 6.0.0
Done

2023-06-20 11:20 UTC, Ashwiniev95 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_script_path : "/opt/sparkjobs/ml-analytics-service/migrations/lib"
This variable is required

2023-06-20 11:20 UTC, Ashwiniev95 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_folder_config : "/opt/sparkjobs/ml-analytics-service/migrations/releases/6.0.0/config/"
Removed

2023-06-20 11:21 UTC, Ashwiniev95 commented on ansible/roles/ml-analytics-service/defaults/main.yml
> +ml_analytics_reports_key : "{{ ml_analytics_reports_key }}"
It is same. so removed this variable

2023-06-20 13:20 UTC, closed without merging