added env variable for user delete flow for ml services
project-sunbird/sunbird-devops pull request #3921
Opened 2023-11-17 09:01 UTC by ankitpws

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-28 09:28 UTC, aks30 requested changes
Reviewed on 28 Nov

2023-11-28 09:28 UTC, aks30 commented on ansible/roles/stack-sunbird/templates/ml-survey-service.env
> +TELEMETRY_ON_OFF={{telemetry_on_off | default("ON")}}
@ankitpws Rename - telemetry_on_off to manage_learn_telemetry_on_off

2023-11-28 09:28 UTC, aks30 commented on ansible/roles/stack-sunbird/templates/ml-survey-service.env
> +USER_DELETE_ON_OFF={{user_delete_on_off | default("ON")}}
@ankitpws - Rename it to manage_learn_ user_delete_on_off

2023-11-28 09:28 UTC, aks30 commented on ansible/roles/stack-sunbird/templates/ml-survey-service.env
> +USER_DELETE_ON_OFF={{user_delete_on_off | default("ON")}}
In this and above file

2023-11-28 10:13 UTC, aks30 approved these changes
Approved.

2023-11-29 05:25 UTC, gandham-santhosh approved these changes

2023-11-29 05:25 UTC, merged